# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20170105160444 on 2017-01-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_needed',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
            preserve_default=False,
        ),
    ]
