# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20170105160444 on 2017-01-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='random',
            field=models.CharField(default='asd', max_length=20),
            preserve_default=False,
        ),
    ]
